# Configuración por defecto para tu Mac (SQLite)
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: storage/development.sqlite3

test:
  <<: *default
  database: storage/test.sqlite3

# Configuración para cuando subas a Render (PostgreSQL)
production:
  primary: &primary_production
    adapter: postgresql
    encoding: unicode
    url: <%= ENV.fetch("DATABASE_URL", "") %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  cable:
    <<: *primary_production
  cache:
    <<: *primary_production
  queue:
    <<: *primary_production